In [4]:
!PIP install kaggle

Requirement already satisfied: kaggle in c:\users\hp\anaconda3\lib\site-packages (1.6.14)
Requirement already satisfied: six>=1.10 in c:\users\hp\anaconda3\lib\site-packages (from kaggle) (1.16.0)
Requirement already satisfied: certifi>=2023.7.22 in c:\users\hp\anaconda3\lib\site-packages (from kaggle) (2024.6.2)
Requirement already satisfied: python-dateutil in c:\users\hp\anaconda3\lib\site-packages (from kaggle) (2.8.2)
Requirement already satisfied: requests in c:\users\hp\anaconda3\lib\site-packages (from kaggle) (2.31.0)
Requirement already satisfied: tqdm in c:\users\hp\anaconda3\lib\site-packages (from kaggle) (4.65.0)
Requirement already satisfied: python-slugify in c:\users\hp\anaconda3\lib\site-packages (from kaggle) (5.0.2)
Requirement already satisfied: urllib3 in c:\users\hp\anaconda3\lib\site-packages (from kaggle) (2.0.7)
Requirement already satisfied: bleach in c:\users\hp\anaconda3\lib\site-packages (from kaggle) (4.1.0)
Requirement already satisfied: packaging in c:\users\hp\anaconda3\lib\site-packages (from bleach->kaggle) (23.1)
Requirement already satisfied: webencodings in c:\users\hp\anaconda3\lib\site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: text-unidecode>=1.3 in c:\users\hp\anaconda3\lib\site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\hp\anaconda3\lib\site-packages (from requests->kaggle) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\hp\anaconda3\lib\site-packages (from requests->kaggle) (3.4)
Requirement already satisfied: colorama in c:\users\hp\anaconda3\lib\site-packages (from tqdm->kaggle) (0.4.6)

In [25]:
import kaggle

In [17]:
!kaggle datasets download ankitbansal06/retail-orders -f orders.csv

Dataset URL: https://www.kaggle.com/datasets/ankitbansal06/retail-orders
License(s): CC0-1.0
orders.csv.zip: Skipping, found more recently modified local copy (use --force to force download)

In [21]:
import zipfile
zip_ref = zipfile.ZipFile('orders.csv.zip')
zip_ref.extractall()
zip_ref.close()

In [49]:
import pandas as pd
df = pd.read_csv('orders.csv',na_values=['Not Available','unknown'])
df['Ship Mode'].unique()

array(['Second Class', 'Standard Class', nan, 'First Class', 'Same Day'],
      dtype=object)

In [53]:
#Changed str into lower & replaced space into underscore
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_')

In [67]:
#Create New Column to See discount
df['discount']=df['list_price']*df['discount_percent']/100

In [71]:
#Create New Column to See sales price
df['sale_price']= df['list_price']-df['discount']

In [75]:
#Create New Column to See profit
df['profit'] = df['sale_price']-df['cost_price']

In [91]:
# convert order date from object to date datatype -->
# df.datatype
#pd.to_datetime(df['order_date'],format='%Y-%m-%d')
#changed datatype in exixting date column
df['order_date']=pd.to_datetime(df['order_date'],format='%Y-%m-%d')

In [119]:
#drop rows and column
#df.drop(columns=['list_price','cost_price','discount_percent'],inplace=True)

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,quantity,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,2,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,5,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,2,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,3,1.2,28.8,-1.2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,2,3.6,86.4,16.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,2,5.2,254.8,34.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,4,0.9,29.1,-0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,2,7.2,232.8,22.8

In [131]:
import sqlalchemy as sql
from sqlalchemy import create_engine
import pandas as pd
!pip install psycopg2

# Replace 'your_username', 'your_password', 'your_host', 'your_port', and 'your_database' with your PostgreSQL credentials
engine = create_engine('postgresql+psycopg2://postgres:123@localhost:5432/SQLPython')
conn = engine.connect()

Collecting psycopg2
  Downloading psycopg2-2.9.9-cp311-cp311-win_amd64.whl.metadata (4.5 kB)
Downloading psycopg2-2.9.9-cp311-cp311-win_amd64.whl (1.2 MB)
   ---------------------------------------- 0.0/1.2 MB ? eta -:--:--
   ----- ---------------------------------- 0.2/1.2 MB 4.6 MB/s eta 0:00:01
   --------- ------------------------------ 0.3/1.2 MB 3.3 MB/s eta 0:00:01
   ------------- -------------------------- 0.4/1.2 MB 3.1 MB/s eta 0:00:01
   ------------------- -------------------- 0.6/1.2 MB 3.2 MB/s eta 0:00:01
   ----------------------- ---------------- 0.7/1.2 MB 3.1 MB/s eta 0:00:01
   ------------------------------ --------- 0.9/1.2 MB 3.3 MB/s eta 0:00:01
   --------------------------------- ------ 1.0/1.2 MB 3.1 MB/s eta 0:00:01
   ------------------------------------ --- 1.1/1.2 MB 3.0 MB/s eta 0:00:01
   ---------------------------------------  1.2/1.2 MB 2.8 MB/s eta 0:00:01
   ---------------------------------------- 1.2/1.2 MB 2.7 MB/s eta 0:00:00
Installing collected packages: psycopg2
Successfully installed psycopg2-2.9.9

In [135]:
df.to_sql('df_orders', con=engine, if_exists='append', index=False)

994